columns:

  - Airline : category
  - Date_of_Journey : category
  - Source : category
  - Destination : category
  - Route : category
  - Dep_Time : category
  - Arrival_Time : category
  - Duration : category
  - Total_Stops : category
  - Additional_Info : category
  - Price : int

numerical_columns:

  - Price 
  
categorical_columns:
  
  - Airline 
  - Date_of_Journey 
  - Source 
  - Destination 
  - Route 
  - Dep_Time 
  - Arrival_Time 
  - Duration 
  - Total_Stops 
  - Additional_Info 
  

drop_columns:
  
  - Total_Stops